### ISSUE TITLE
Add Renavam Generator

### ISSUE THREAD

**Issue by marquinhusgoncalves-zz** [marcopelegrini/inventor#1]
Add Renavam Generator in plugin or other service. What do you thing about?

Suggestion
https://www.4devs.com.br/gerador_de_renavam

**Comment by marcopelegrini** [comment]
It's fine, just make the changes and open a pull request

**Comment by marquinhusgoncalves-zz** [comment]
Perfect....

**Comment by marquinhusgoncalves-zz** [comment]
PR open https://github.com/marcopelegrini/inventor/pull/2

**Comment by marquinhusgoncalves-zz** [comment]
Como funciona, você faz a publicação ou gero um .rar e consigo dar um update no que eu já tenho?

**Comment by marcopelegrini** [comment]
It's published now. Check Chrome Webstore
